# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AutoHealthReport

on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron: '9 0 * * *'

permissions:
  contents: read

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install requests
    - name: Auto-report
      env:
        STUID: ${{ secrets.STUID }}
        PW: ${{ secrets.PW }}
#         MAIL_ENABLE: ${{ secrets.MAIL_ENABLE }}
        MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
        MAIL_PW: ${{ secrets.MAIL_PW }}
        MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
      run: python main.py
